declare namespace pins {
    //% fixedInstance shim=pxt::getPin(PIN_LED_B)
    const PIN_LED_BLUE: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_LED_G)
    const PIN_LED_GREEN: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_LED_R)
    const PIN_LED_RED: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_RX)
    const RX: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_TX)
    const TX: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_MISO)
    const MISO: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_MOSI)
    const MOSI: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_SCK)
    const SCK: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_SCL)
    const SCL: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_SDA)
    const SDA: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_LED2)
    const PIN_LED2: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_LED3)
    const PIN_LED3: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_BTN_A)
    const PIN_BTN1: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_BTN_B)
    const PIN_BTN2: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPin(PIN_WIFI_TX)
    const PIN_ESP_TX: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_RX)
    const PIN_ESP_RX: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_RESET)
    const PIN_ESP_RESET: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_MOSI)
    const PIN_ESP_MOSI: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_MISO)
    const PIN_ESP_MISO: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_SCK)
    const PIN_ESP_SCK: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_CS)
    const PIN_ESP_CS: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_GPIO0)
    const PIN_ESP_GPIO0: DigitalInOutPin;
	//% fixedInstance shim=pxt::getPin(PIN_WIFI_BUSY)
    const PIN_ESP_BUSY: DigitalInOutPin;
}
